CBD-4887: Clarify encoding of index keys on create index
couchbaselabs/sdk-rfcs pull request #116
Opened 2022-06-28 08:32 UTC by chvck

2022-08-18 18:23 UTC, dnault requested changes

2022-08-18 18:23 UTC, dnault commented on rfc/0054-sdk3-management-apis.md
> +    Note: this means that keywords like ASC/DESC cannot be used.
Is it worth adding an example that shows user input and the resulting query? (Personally, I'm confused about what it means to escape keys individually, and why this means keywords can't be used).

2022-10-04 12:07 UTC, avsej approved these changes

2023-02-01 18:43 UTC, dnault approved these changes

2023-02-09 09:03 UTC, brett19 approved these changes

2023-02-09 09:07 UTC, merged